# Tensorflow Basics

In this notebook, we are going to cover some of the most fundamental concepts of `tensors` using [TensorFlow](https://www.tensorflow.org/).

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using `@tf.function` (a way to speed up regular Python functions)
* Using GPUs with TensorFlow (or TPUs) to do faster numerical computing

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.6.0'

## Introduction to [Tensors](https://www.tensorflow.org/guide/tensor)

### Constants

Let's show how to create simple constants with Tensorflow, which TF stores as tensor objects.

#### Strings

In [3]:
# Create a constant tensor with a data type of string
hello = tf.constant('Hello World')
hello

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello World'>

In [4]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [5]:
# Check the number of dimensions of a string constant tensor
hello.ndim

0

#### Integers

In [6]:
# Create a constant tensor with data type of integer
scalar = tf.constant(100)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=100>

In [7]:
type(scalar)

tensorflow.python.framework.ops.EagerTensor

In [8]:
# Check the number of dimensions of an integer constant tensor
scalar.ndim

0

#### Vectors

In [9]:
vector = tf.constant([1, 2, 3, 4])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [10]:
type(vector)

tensorflow.python.framework.ops.EagerTensor

In [11]:
vector.ndim

1

#### Matrix (has nore than 1 dimension)

In [12]:
matrix = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [13]:
type(matrix)

tensorflow.python.framework.ops.EagerTensor

In [14]:
matrix.ndim

2

In [15]:
# Create another matrix while specifying data type
another_matrix = tf.constant(
    [
        [1.2, 2.3, 3.4],
        [6., 7., 8.],
        [9, 10, 11]
    ],
    dtype=tf.float16 # Specify the data type with dtype parameter
)
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[ 1.2,  2.3,  3.4],
       [ 6. ,  7. ,  8. ],
       [ 9. , 10. , 11. ]], dtype=float16)>

In [16]:
type(another_matrix)

tensorflow.python.framework.ops.EagerTensor

In [17]:
another_matrix.ndim

2

#### Multi-Axis Tensors (multi-dimension numerical arrays)

Tensors may have more than 2 axes.

In [18]:
# Create a 3-dim tensor (also called rank-3 tensor, or 3-axis tensor)
rank_3_tensor = tf.constant([
    [
        [0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]
    ],
    [
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]
    ],
])
rank_3_tensor

<tf.Tensor: shape=(2, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])>

In [19]:
type(rank_3_tensor)

tensorflow.python.framework.ops.EagerTensor

In [20]:
rank_3_tensor.ndim

3

<font color=magenta>
Summary:

* Scalar: a single number
* Vector: a 1-dimensional array of numbers
* Matrix: a 2-dimensional array of numbers
* Tensor: an `n-dimensional` array of numbers (where `n` can be any numbers `0`, `1`, `2`, `3`, ...)
</font>

### Variables

[TensorFlow variables](https://www.tensorflow.org/guide/variable) are defined via the [tf.Variable](https://www.tensorflow.org/api_docs/python/tf/Variable) class and are normally used to save state data for program manipulates.

#### Integers

In [21]:
# Create a variable holding integers
int_var = tf.Variable(1)
int_var

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [22]:
# Print out basic information of the newly created variable
print('Shape:', int_var.shape)
print('DType:', int_var.dtype)
print('As NumPy:', int_var.numpy())

Shape: ()
DType: <dtype: 'int32'>
As NumPy: 1


In [23]:
# Change value of the variable (wrong way)
# We must not directly assign values to a TensorFlow variable
# like `int_var = 2`, because this will change its data type to int
# Instead, use the tf.Variable.assign() method to assign a new value
int_var.assign(2)
int_var

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>

#### Vectors

In [24]:
# Define a variable containing a vector of boolean values
bool_var = tf.Variable([True, False, True, True, False])
bool_var

<tf.Variable 'Variable:0' shape=(5,) dtype=bool, numpy=array([ True, False,  True,  True, False])>

In [25]:
# Get the value of the variable
bool_var.value()

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([ True, False,  True,  True, False])>

In [26]:
# Define a variable saving a vector of floats
float_var = tf.Variable([1., 2., 3., 4.])
float_var

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

In [27]:
# Access value of the second element in the float vector
float_var[1]

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [28]:
# Change the value of the second element in the float vector
float_var[1].assign(9.)
float_var

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1., 9., 3., 4.], dtype=float32)>

In [29]:
# Convert a variable to a tensor
tf.convert_to_tensor(float_var)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 9., 3., 4.], dtype=float32)>

In [30]:
# Find the index of the highest value
tf.argmax(float_var)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [31]:
# Create a new tensor by copying and reshaping the original variable
float_tensor = tf.reshape(float_var, [2, 2])
float_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 9.],
       [3., 4.]], dtype=float32)>

In [32]:
# Check that the original variable's shape doesn't change
print(float_var.shape)
float_var

(4,)


<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1., 9., 3., 4.], dtype=float32)>

#### Matrices and Multi-Dimensional Arrays

In [33]:
# Create a TensorFlow variable holding a two-dim array of ints
matrix_var = tf.Variable([
    [1, 2, 3],
    [4, 5, 6]
])
matrix_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [34]:
# Access value of an element in a 2-dim-array holding TF var
matrix_var[0, 2]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [35]:
# Create a TensorFlow variable containing a three-dim array of ints
three_dim_var = tf.Variable([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [10, 20, 30],
        [40, 50, 60]
    ],
])
three_dim_var

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]]])>

In [36]:
# Access value of one element in a 3-dim-array holding TF var
three_dim_var[1][1][1]

<tf.Tensor: shape=(), dtype=int32, numpy=50>

#### Operatios

Each tensofFlow variable is actually backed by a [tf.Tensor](https://www.tensorflow.org/api_docs/python/tf/Tensor) and most tensor operations work on variables.

In [37]:
# Define two TF variables
a = tf.Variable([
    [1, 2, 3],
    [4, 5, 6]
])

b = tf.Variable([
    [10, 20, 30],
    [40, 50, 60]
])

a, b

(<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>,
 <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
 array([[10, 20, 30],
        [40, 50, 60]])>)

In [38]:
# Add two variables
a + b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 22, 33],
       [44, 55, 66]])>

In [39]:
# Sub two variables
b - a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 9, 18, 27],
       [36, 45, 54]])>

In [40]:
# Mul two variables
a * b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 10,  40,  90],
       [160, 250, 360]])>

In [41]:
# Multiply a variable with a constant
a * 2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]])>

In [42]:
# Div two variables
b / a

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[10., 10., 10.],
       [10., 10., 10.]])>

In [43]:
# Define a new variable based on the value of another variable
c = tf.Variable(a)
print(c)

# Then assign c to the sum of its current value with the value of a
c.assign_add(a)
print(c)

# Then multiply c by 2
c.assign(c.numpy() * 2)
c

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]])>


<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 4,  8, 12],
       [16, 20, 24]])>