# Tensorflow Basics

In this notebook, we are going to cover some of the most fundamental concepts of `tensors` using [TensorFlow](https://www.tensorflow.org/).

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using `@tf.function` (a way to speed up regular Python functions)
* Using GPUs with TensorFlow (or TPUs) to do faster numerical computing

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.6.0'

## Introduction to [Tensors](https://www.tensorflow.org/guide/tensor)

### Constants

Let's show how to create simple constants with Tensorflow, which TF stores as tensor objects.

#### Strings

In [3]:
# Create a constant tensor with a data type of string
hello = tf.constant('Hello World')
hello

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello World'>

In [4]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [5]:
# Check the number of dimensions of a string constant tensor
hello.ndim

0

#### Integers

In [6]:
# Create a constant tensor with data type of integer
scalar = tf.constant(100)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=100>

In [7]:
type(scalar)

tensorflow.python.framework.ops.EagerTensor

In [8]:
# Check the number of dimensions of an integer constant tensor
scalar.ndim

0

#### Vectors

In [9]:
vector = tf.constant([1, 2, 3, 4])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [10]:
type(vector)

tensorflow.python.framework.ops.EagerTensor

In [11]:
vector.ndim

1

#### Matrix (has nore than 1 dimension)

In [12]:
matrix = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [13]:
type(matrix)

tensorflow.python.framework.ops.EagerTensor

In [14]:
matrix.ndim

2

In [15]:
# Create another matrix while specifying data type
another_matrix = tf.constant(
    [
        [1.2, 2.3, 3.4],
        [6., 7., 8.],
        [9, 10, 11]
    ],
    dtype=tf.float16 # Specify the data type with dtype parameter
)
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[ 1.2,  2.3,  3.4],
       [ 6. ,  7. ,  8. ],
       [ 9. , 10. , 11. ]], dtype=float16)>

In [16]:
type(another_matrix)

tensorflow.python.framework.ops.EagerTensor

In [17]:
another_matrix.ndim

2

#### Multi-Axis Tensors (multi-dimension numerical arrays)

Tensors may have more than 2 axes.

In [18]:
# Create a 3-dim tensor (also called rank-3 tensor, or 3-axis tensor)
rank_3_tensor = tf.constant([
    [
        [0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]
    ],
    [
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]
    ],
])
rank_3_tensor

<tf.Tensor: shape=(2, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])>

In [19]:
type(rank_3_tensor)

tensorflow.python.framework.ops.EagerTensor

In [20]:
rank_3_tensor.ndim

3

<font color=magenta>
Summary:

* Scalar: a single number
* Vector: a 1-dimensional array of numbers
* Matrix: a 2-dimensional array of numbers
* Tensor: an `n-dimensional` array of numbers (where `n` can be any numbers `0`, `1`, `2`, `3`, ...)
</font>