# Introduction to NumPy

[NumPy](https://numpy.org/) **(Numerical Python)** is a very popular [Python](https://www.python.org/) library providing variety ways to do scientific computation with numerical `n-dimentional` arrays.

In [1]:
# Import NumPy
import numpy as np

## Creating NumPy arrays

In [2]:
# Create a one-dimensional NumPy array using a Python list
a1 = np.array([1, 2, 3, 4, 5])
a1

array([1, 2, 3, 4, 5])

In [3]:
# Check the type of the above NumPy array
type(a1)

numpy.ndarray

In [4]:
# Check the data type of elements inside the above NumPy array
a1.dtype

dtype('int32')

In [5]:
# Check the shape of the above NumPy array
a1.shape

(5,)

In [6]:
# Create a two-dimensional NumPy array
a2 = np.array([[1.2, 2.3, 3.4, 4.5], [5.6, 6.7, 7.8, 8.9]])
a2

array([[1.2, 2.3, 3.4, 4.5],
       [5.6, 6.7, 7.8, 8.9]])

In [7]:
# Check the type of the above two-dimensional NumPy array
type(a2)

numpy.ndarray

In [8]:
# Check the data type of elements inside the above two-dimensional NumPy array
a2.dtype

dtype('float64')

In [9]:
# Check the shape of the above two-dimensional NumPy array
a2.shape

(2, 4)

In [10]:
# Create a three-dimensional NumPy array
a3 = np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8]],
    [[9, 10, 11, 12], [13, 14, 15, 16]],
    [[17, 18, 19, 20], [21, 22, 23, 24]],
])
a3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [11]:
# Check the type of the above three-dimensional NumPy array
type(a3)

numpy.ndarray

In [12]:
# Check the data type of elements inside the above three-dimensional NumPy array
a3.dtype

dtype('int32')

In [13]:
# Check the shape of the above three-dimensional NumPy array
a3.shape

(3, 2, 4)

## Note: Vectors, Matrices, Tensors
* A `vector` = one-dimensional array
* A `matrix` = two-dimensional array
* A `tensor` = 3-D or higher dimensional array

In [14]:
# Create an array filled with 0's
zerosArray = np.zeros(3)
zerosArray

array([0., 0., 0.])

In [15]:
# Create an array filled with 1's
onesArray = np.ones(4)
onesArray

array([1., 1., 1., 1.])

In [16]:
# Create an array with a range of elements
rangeArray = np.arange(4)
rangeArray

array([0, 1, 2, 3])

In [17]:
# Create an array with oddly-spaced intervals
oddRangeArray = np.arange(3, 10, 2)
oddRangeArray

array([3, 5, 7, 9])

In [18]:
# Create an array with values that are spaced linearly in a specified interval
linearArray = np.linspace(2, 20, num=4)
linearArray

array([ 2.,  8., 14., 20.])

## Specifying data type

While the default data type is floating point (`np.float64`), you can explicitly specify which data type you want using the `dtype` keyword.

In [19]:
integerArray = np.arange(1, 9, dtype=int)
print(integerArray)
print(integerArray.dtype)

[1 2 3 4 5 6 7 8]
int32


## Adding, removing and sorting

### Adding elements using [np.concatenate](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html)

In [20]:
# Use np.concatenate() to combine two arrays into a single array
arr1 = np.array([3, 2, 5])
arr2 = np.array([1, 6, 9])
arr3 = np.concatenate((arr1, arr2))
print(arr1)
print(arr2)
arr3

[3 2 5]
[1 6 9]


array([3, 2, 5, 1, 6, 9])

In [21]:
# Concatenate two-dimensional arrays
arr4 = np.array([[1, 2, 3], [4, 5, 6]])
arr5 = np.array([[7, 8, 9], [0, 0, 0]])
arr6 = np.concatenate((arr4, arr5)) # same as np.concatenate((arr4, arr5), axis=0)
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 0, 0]])

In [22]:
arr7 = np.concatenate((arr4, arr5), axis=1)
arr7

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 0, 0, 0]])

### Removing elements using [np.delete](https://numpy.org/doc/stable/reference/generated/numpy.delete.html)

In [23]:
# Define a one-dimensional array
arr8 = np.array([0, 1, 2, 3, 4, 5])

# Delete element at index 3 (index ranges from 0)
arr8AfterDeleted = np.delete(arr8, 3)

print(arr8)
arr8AfterDeleted

[0 1 2 3 4 5]


array([0, 1, 2, 4, 5])

In [24]:
# Define a two dimensional array
arr9 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Delete the second row [5, 6, 7, 8]
# 1 - means delete element at index 1 (index starting from 0)
# axis=0 - means use 0th axis (first dimension) along which to delete the subarray
arr9AfterDeletingRow = np.delete(arr9, 1, axis=0)

print(arr9)
arr9AfterDeletingRow

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [25]:
# Delete the fourth column [4, 8, 12]
# 3 - means delete element at index 4 (index starting from 0)
# axis=1 - means use 1th axis (second dimension) along which to delete the subarray
arr9AfterDeletingColumn = np.delete(arr9, 3, axis=1)

print(arr9)
arr9AfterDeletingColumn

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [26]:
# Use mask to delete elements
arr10 = np.arange(0, 10)
print(arr10)

# Define a mask
mask = np.ones(len(arr10), dtype=bool)
print(mask)

# Specify that elements at indices 1, 3, 8 should be deleted
mask[[1, 3, 8]] = False
print(mask)

# Delete operation with mask
arr10AfterDeleted = arr10[mask, ...]
arr10AfterDeleted

[0 1 2 3 4 5 6 7 8 9]
[ True  True  True  True  True  True  True  True  True  True]
[ True False  True False  True  True  True  True False  True]


array([0, 2, 4, 5, 6, 7, 9])

### Sorting elements using [np.sort](https://numpy.org/doc/stable/reference/generated/numpy.sort.html)

In [27]:
# Sort 1-D array
arr11 = np.array([3, 2, 9, 6, 7, 1, 0, 5, 4])
np.sort(arr11)

array([0, 1, 2, 3, 4, 5, 6, 7, 9])

In [28]:
# Sort 2-D array
arr12 = np.array([
    [3, 2, 8, 5, 7],
    [0, 9, 1, 4, 6]
])

In [29]:
# Sort along the last axis
np.sort(arr12)

array([[2, 3, 5, 7, 8],
       [0, 1, 4, 6, 9]])

In [30]:
# Sort along the first axis
np.sort(arr12, axis=0)

array([[0, 2, 1, 4, 6],
       [3, 9, 8, 5, 7]])

In [31]:
# Sort the flattened array
np.sort(arr12, axis=None)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# Use the order keyword to specify a field to use when sorting a structured array
dtype = [('name', 'S10'), ('price', float), ('quantity', int)]
values = [
    ('Macbook', 2400.34, 1),
    ('MS Surface', 3000.45, 2),
    ('Chromebooks', 1900.67, 3)
]
arr13 = np.array(values, dtype) # create a structured array
arr13

array([(b'Macbook', 2400.34, 1), (b'MS Surface', 3000.45, 2),
       (b'Chromebook', 1900.67, 3)],
      dtype=[('name', 'S10'), ('price', '<f8'), ('quantity', '<i4')])

In [33]:
# Sort by 'name'
np.sort(arr13, order='name')

array([(b'Chromebook', 1900.67, 3), (b'MS Surface', 3000.45, 2),
       (b'Macbook', 2400.34, 1)],
      dtype=[('name', 'S10'), ('price', '<f8'), ('quantity', '<i4')])

In [34]:
# Sort by 'price', then 'quantity' if 'price's are equal
np.sort(arr13, order=['price', 'quantity'])

array([(b'Chromebook', 1900.67, 3), (b'Macbook', 2400.34, 1),
       (b'MS Surface', 3000.45, 2)],
      dtype=[('name', 'S10'), ('price', '<f8'), ('quantity', '<i4')])

## Slicing, stacking and splitting arrays

In [35]:
# Slice an existing array to get a new sub-array
arr14 = np.array([0, 1, 2, 3, 4, 5])
arr14Sub = arr14[1: 4]
print(arr14)
arr14Sub

[0 1 2 3 4 5]


array([1, 2, 3])

In [36]:
# Vertically stack two arrays
arr15_1 = np.array([
    [0, 1],
    [2, 3]
])

arr15_2 = np.array([
    [4, 5],
    [6, 7]
])

arr15_vertically_stacked = np.vstack((arr15_1, arr15_2))
arr15_vertically_stacked

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [37]:
# Horizontally stack two arrays
arr15_horizontally_stacked = np.hstack((arr15_1, arr15_2))
arr15_horizontally_stacked

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [38]:
# Split a big array into smaller ones
arr16 = np.arange(1, 19).reshape(2, 9)
print(arr16)

# Split the array into three equally shaped arrays
arr16_3equally_shaped = np.hsplit(arr16, 3)
arr16_3equally_shaped

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]


[array([[ 1,  2,  3],
        [10, 11, 12]]),
 array([[ 4,  5,  6],
        [13, 14, 15]]),
 array([[ 7,  8,  9],
        [16, 17, 18]])]

In [39]:
# Split the array after the third column
arr16_3rd = np.hsplit(arr16, [3])
arr16_3rd

[array([[ 1,  2,  3],
        [10, 11, 12]]),
 array([[ 4,  5,  6,  7,  8,  9],
        [13, 14, 15, 16, 17, 18]])]

In [40]:
# Split the array after the 3rd and go up to 7th column (4th, 5th, 6th, 7th)
arr16_3rd_6th = np.hsplit(arr16, [3, 7])
arr16_3rd_6th

[array([[ 1,  2,  3],
        [10, 11, 12]]),
 array([[ 4,  5,  6,  7],
        [13, 14, 15, 16]]),
 array([[ 8,  9],
        [17, 18]])]

## Copying arrays

### Deep copy with [np.copy](https://numpy.org/doc/stable/reference/generated/numpy.copy.html)

In [41]:
# Using the copy method will make a complete copy of the array and its data (a deep copy)
arr17 = np.array([1, 2, 3])
arr17_deepCopy = arr17.copy()

# After deep copy
print(arr17)
print(arr17_deepCopy)

arr17_deepCopy[0] = 100

print('\n')
print(arr17)
print(arr17_deepCopy)

[1 2 3]
[1 2 3]


[1 2 3]
[100   2   3]


### Shallow copy with [np.view](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.view.html)

The view method to create a new array object that looks at the same data as the original array (a shallow copy).

Views are an important NumPy concept! NumPy functions, as well as operations like indexing and slicing, will return views whenever possible. This saves memory and is faster (no copy of the data has to be made). However it’s important to be aware of this - modifying data in a view also modifies the original array!

In [42]:
arr18 = np.arange(1, 19)
print(arr18)

# Creating a slice of the original arr18 will create a view
arr18_slice_view = arr18[3: 9]
print(arr18_slice_view)

# Modifying the view will affect both the view itself and the original array
arr18_slice_view[0] = 400
print(arr18)
print(arr18_slice_view)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[4 5 6 7 8 9]
[  1   2   3 400   5   6   7   8   9  10  11  12  13  14  15  16  17  18]
[400   5   6   7   8   9]


In [43]:
arr19 = np.arange(1, 25).reshape(3, 8)
print(arr19)

arr19_reshaped_view = arr19.view()
print(f'\n{arr19_reshaped_view}')

arr19_reshaped_view = arr19_reshaped_view.reshape(4, 6)
print(f'\n{arr19_reshaped_view}')

# Changing the view 'arr19_reshaped_view' will also affect to the original 'arr19' array
arr19_reshaped_view[1, 2] = 900
print(f'\n{arr19}')
print(f'\n{arr19_reshaped_view}')

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

[[  1   2   3   4   5   6   7   8]
 [900  10  11  12  13  14  15  16]
 [ 17  18  19  20  21  22  23  24]]

[[  1   2   3   4   5   6]
 [  7   8 900  10  11  12]
 [ 13  14  15  16  17  18]
 [ 19  20  21  22  23  24]]


## Basic operations

In [44]:
arr20_1 = np.arange(1, 16).reshape(3, 5)
arr20_1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [45]:
arr20_2 = np.arange(2, 31, 2).reshape(3, 5)
arr20_2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

### Adding two arrays

In [46]:
arr20_add = arr20_1 + arr20_2
arr20_add

array([[ 3,  6,  9, 12, 15],
       [18, 21, 24, 27, 30],
       [33, 36, 39, 42, 45]])

### Substracting two arrays

In [47]:
arr20_sub = arr20_1 - arr20_2
arr20_sub

array([[ -1,  -2,  -3,  -4,  -5],
       [ -6,  -7,  -8,  -9, -10],
       [-11, -12, -13, -14, -15]])

### Multiplying two arrays

In [48]:
arr20_mul = arr20_1 * arr20_2
arr20_mul

array([[  2,   8,  18,  32,  50],
       [ 72,  98, 128, 162, 200],
       [242, 288, 338, 392, 450]])

### Dividing two arrays

In [49]:
arr20_div = arr20_1 / arr20_2
arr20_div

array([[0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5]])

### Summing up elements

In [50]:
print(arr20_1)

# Sum up all elements
arr20_1.sum()

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


120

In [51]:
# Sum up elements of each column
arr20_1.sum(axis=0)

array([18, 21, 24, 27, 30])

In [52]:
# Sum up elements of each row
arr20_1.sum(axis=1)

array([15, 40, 65])